# Generated by Django 5.0.8 on 2025-11-30 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversation_message'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='steam_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime_forever', models.IntegerField(default=0)),
                ('platform', models.CharField(default='Steam', max_length=50)),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('completed', 'Completed'), ('backlog', 'Backlog'), ('dropped', 'Dropped')], default='backlog', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='core.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
