# Generated by Django 5.2.8 on 2025-12-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_steam_id_libraryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryentry',
            name='status',
            field=models.CharField(choices=[('unplayed', 'Unplayed'), ('playing', 'Playing'), ('replaying', 'Replaying'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='unplayed', max_length=20),
        ),
    ]
