# Generated by Django 5.2.8 on 2025-12-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
