# Generated by Django 5.2.9 on 2025-12-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_review'),
        ('core', '0008_remove_post_parent_post_remove_post_parent_review_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
