# Generated by Django 5.2.9 on 2025-12-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
