# Generated by Django 5.2.11 on 2026-02-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryentry',
            name='status',
            field=models.CharField(choices=[('unplayed', 'Unplayed'), ('plan_to_play', 'Plan to Play'), ('playing', 'Playing'), ('replaying', 'Replaying'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='unplayed', max_length=20),
        ),
    ]
