# Generated by Django 5.2.11 on 2026-03-09 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_libraryentry_status'),
        ('core', '0026_post_game_tag_post_platform_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_hours', models.JSONField(blank=True, default=list)),
                ('media_preferences', models.JSONField(blank=True, default=dict)),
                ('interaction_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('play_request', 'Play Request')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'interaction_type', '-created_at'], name='api_postint_user_id_35c5e2_idx'), models.Index(fields=['post', 'interaction_type'], name='api_postint_post_id_37e208_idx'), models.Index(fields=['post', '-created_at'], name='api_postint_post_id_e29a9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostScoreCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_score', models.FloatField(default=0.0)),
                ('virality_score', models.FloatField(default=0.0)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('play_request_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_cache', to='core.post')),
            ],
            options={
                'indexes': [models.Index(fields=['-engagement_score'], name='api_postsco_engagem_da8802_idx')],
            },
        ),
    ]
