# Generated by Django 5.2.12 on 2026-03-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_libraryentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryentry',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='status',
            field=models.CharField(choices=[('unplayed', 'Unplayed'), ('plan_to_play', 'Plan to Play'), ('playing', 'Playing'), ('replaying', 'Replaying'), ('completed', 'Completed'), ('dropped', 'Dropped')], db_index=True, default='unplayed', max_length=20),
        ),
    ]
