# Generated by Django 5.2.12 on 2026-06-02 19:02

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_libraryentry_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.JSONField(blank=True, default=api.models.default_user_settings),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('support', 'Support Contact'), ('bug', 'Bug Report')], default='support', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('steps_to_reproduce', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
