# Generated by Django 5.2.12 on 2026-07-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xbox_gamertag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
