# Generated by Django 5.2.12 on 2026-06-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_conversationmember_invited_by_and_more'),
        ('api', '0020_followrequest'),
    ]

    operations = [
    ]
