# Generated by Django 5.2.12 on 2026-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_xbox_gamertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryentry',
            name='steam_playtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='xbox_playtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='platform',
            field=models.CharField(default='Steam', max_length=100),
        ),
    ]
