# Generated by Django 5.2.12 on 2026-07-16 07:47

from django.db import migrations, models


def backfill_is_private(apps, schema_editor):
    # The new column defaults to False for every existing row; without this, every user who had
    # actually set settings['privateProfile'] = True would suddenly appear public everywhere
    # (feed/search) until they resaved their settings. Chunked to avoid loading the whole table.
    User = apps.get_model('api', 'User')
    private_ids = list(
        User.objects.filter(settings__privateProfile=True).values_list('id', flat=True)
    )
    for i in range(0, len(private_ids), 1000):
        User.objects.filter(id__in=private_ids[i:i + 1000]).update(is_private=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_pendingregistration_failed_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(backfill_is_private, noop_reverse),
    ]
