# Generated by Django 5.2.12 on 2026-07-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_libraryentry_steam_playtime_and_more'),
        ('api', '0024_perf_indexes_and_privacy_flag'),
    ]

    operations = [
    ]
