# Generated by Django 5.2.12 on 2026-07-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_perf_indexes_and_privacy_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
