# Generated by Django 5.2.12 on 2026-07-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20260716_1238'),
        ('api', '0026_pendingemailchange'),
    ]

    operations = [
    ]
