# Generated by Django 5.2.12 on 2026-07-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20260719_1140'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0069_playtestfeedback_ptf_proj_pin_sub_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='msg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notif_recip_created_idx'),
        ),
    ]
