# Generated by Django 5.2.12 on 2026-08-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_conversationreport_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('mention', 'Mention'), ('reply', 'Reply'), ('comment_review', 'Comment on Review'), ('repost', 'Repost'), ('quote', 'Quote'), ('follow', 'Follow'), ('follow_request', 'Follow Request'), ('follow_request_accepted', 'Follow Request Accepted'), ('project_invite', 'Project Invite'), ('project_invite_accepted', 'Project Invite Accepted'), ('project_followed', 'Project Followed'), ('org_invite', 'Organisation Invite'), ('org_invite_accepted', 'Organisation Invite Accepted'), ('org_ownership_transfer_to_you', 'Org Ownership Transfer To You'), ('org_ownership_transfer_confirmation', 'Org Ownership Transfer Confirmation'), ('group_invite', 'Group Chat Invite'), ('message_request', 'Message Request'), ('steam_sync_success', 'Steam Sync Success'), ('steam_sync_failed', 'Steam Sync Failed'), ('unknown', 'Unknown')], db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='recent_actor_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
