# Generated by Django 5.2.12 on 2026-08-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_notification_notification_type'),
        ('core', '0071_post_poll_expires_at_pollvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='core.post')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='posthashtag_created_idx')],
                'unique_together': {('post', 'tag')},
            },
        ),
    ]
