# Generated by Django 5.2.8 on 2025-12-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_gif_url_post_media_file_post_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poll_options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
