# Generated by Django 5.2.8 on 2025-12-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_poll_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
