# Generated by Django 5.2.8 on 2025-12-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
