# Generated by Django 5.2.9 on 2025-12-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='text_comment',
        ),
        migrations.AddField(
            model_name='review',
            name='contains_spoilers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(),
        ),
    ]
