# Generated by Django 5.2.9 on 2025-12-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_review_text_comment_review_contains_spoilers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='contains_spoilers',
        ),
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='review',
            name='text_comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
