# Generated by Django 5.2.9 on 2025-12-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_review_contains_spoilers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
