# Generated by Django 5.2.9 on 2025-12-22 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_post_review_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rss_url', models.URLField()),
                ('category', models.CharField(choices=[('invest', 'Investment'), ('devs', 'Development'), ('hardware', 'Hardware'), ('general', 'General')], default='general', max_length=20)),
                ('icon', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=1000, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField()),
                ('category', models.CharField(db_index=True, max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.newssource')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-pub_date'],
            },
        ),
    ]
