# Generated by Django 5.2.8 on 2026-02-04 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_postmedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('investor_type', models.CharField(choices=[('vc', 'Venture Capital'), ('publisher', 'Publisher'), ('angel', 'Angel Investor'), ('grant', 'Grant / Fund'), ('accelerator', 'Accelerator')], max_length=20)),
                ('looking_for', models.TextField()),
                ('ticket_size', models.CharField(help_text='e.g. $100k+', max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('rpg', 'RPG'), ('fps', 'FPS'), ('strategy', 'Strategy'), ('simulation', 'Simulation'), ('adventure', 'Adventure'), ('platformer', 'Platformer'), ('puzzle', 'Puzzle'), ('other', 'Other')], max_length=20)),
                ('platform', models.CharField(choices=[('pc', 'PC'), ('console', 'Console'), ('mobile', 'Mobile'), ('vr_ar', 'VR/AR'), ('web', 'Web'), ('multi', 'Multi-platform')], max_length=20)),
                ('funding_goal', models.CharField(help_text='e.g. $50k-$100k', max_length=100)),
                ('stage', models.CharField(choices=[('concept', 'Concept'), ('prototype', 'Prototype'), ('vertical_slice', 'Vertical Slice'), ('production', 'In Production'), ('alpha', 'Alpha'), ('beta', 'Beta'), ('early_access', 'Early Access')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pitches/')),
                ('pitch_deck_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
