# Generated by Django 5.2.11 on 2026-02-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_investorcall_pitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
