# Generated by Django 5.2.11 on 2026-03-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_game_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_posts', to='core.game'),
        ),
        migrations.AddField(
            model_name='post',
            name='platform_tag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
