# Generated by Django 5.2.11 on 2026-04-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_game_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_appid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
