# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_steam_appid_to_game'),
        ('core', '0026_alter_game_title_alter_news_pub_date_and_more'),
    ]

    operations = [
    ]
