# Generated by Django 5.2.12 on 2026-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=20),
        ),
    ]
