# Generated by Django 5.2.12 on 2026-05-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_projectmember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='post_type',
            field=models.CharField(choices=[('job', 'Job Offering'), ('talent', 'Talent Profile')], default='job', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
