# Generated by Django 5.2.12 on 2026-05-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_jobposting_post_type_jobposting_tech_stack'),
        ('core', '0030_projectfollow'),
    ]

    operations = [
    ]
