# Generated by Django 5.2.12 on 2026-06-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_bookmark'),
        ('core', '0031_merge_20260517_1602'),
    ]

    operations = [
    ]
