# Generated by Django 5.2.12 on 2026-06-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_drop_unused_platform_tag'),
        ('core', '0032_merge_0031_bookmark_0031_merge_20260517_1602'),
    ]

    operations = [
    ]
