# Generated by Django 5.2.12 on 2026-06-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_merge_20260606_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='core.post'),
        ),
    ]
