# Generated by Django 5.2.12 on 2026-06-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_game_detail_fields'),
        ('core', '0034_post_repost_parent'),
    ]

    operations = [
    ]
