# Generated by Django 5.2.12 on 2026-06-10 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_0034_game_detail_fields_0034_post_repost_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_parent_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='core.review'),
        ),
    ]
