# Generated by Django 5.2.12 on 2026-06-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_post_repost_parent_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('reviews', 'Reviews'), ('gameplay', 'Gameplay'), ('news', 'News'), ('discussion', 'Discussion'), ('memes', 'Memes'), ('esports', 'Esports'), ('indie', 'Indie'), ('devlogs', 'Dev Logs'), ('tips', 'Tips & Guides'), ('general', 'General')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='trending_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
