# Generated by Django 5.2.12 on 2026-06-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_playthrough_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hltb_completionist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='hltb_main',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='hltb_main_extra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='metacritic_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
