# Generated by Django 5.2.12 on 2026-06-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_post_category_post_trending_score'),
        ('core', '0039_reset_details_fetched_for_stats'),
    ]

    operations = [
    ]
