# Generated by Django 5.2.12 on 2026-06-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_assetregistryitem_gdddatatable_gdddocument_and_more'),
    ]

    operations = [
        # First, drop any unique_together options/constraints
        migrations.AlterUniqueTogether(
            name='localisationkey',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='translationvote',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='usertranslationstats',
            unique_together=None,
        ),
        
        # Now create WorkspaceState
        migrations.CreateModel(
            name='WorkspaceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        
        # Now safely remove fields
        migrations.RemoveField(
            model_name='gdddatatable',
            name='project',
        ),
        migrations.RemoveField(
            model_name='gdddocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gdddocument',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='gdddocument',
            name='project',
        ),
        migrations.RemoveField(
            model_name='gdddocumentcomment',
            name='document',
        ),
        migrations.RemoveField(
            model_name='gdddocumentcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kanbantask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='kanbantask',
            name='project',
        ),
        migrations.RemoveField(
            model_name='localisationkey',
            name='project',
        ),
        migrations.RemoveField(
            model_name='localisationtranslation',
            name='localisation_key',
        ),
        migrations.RemoveField(
            model_name='localisationtranslation',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='localisationtranslation',
            name='suggested_by',
        ),
        migrations.RemoveField(
            model_name='translationvote',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='playtestfeedback',
            name='project',
        ),
        migrations.RemoveField(
            model_name='playtestfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectmilestone',
            name='project',
        ),
        migrations.RemoveField(
            model_name='translationvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertranslationstats',
            name='project',
        ),
        migrations.RemoveField(
            model_name='usertranslationstats',
            name='user',
        ),
        
        # Now delete models
        migrations.DeleteModel(
            name='AssetRegistryItem',
        ),
        migrations.DeleteModel(
            name='GDDDataTable',
        ),
        migrations.DeleteModel(
            name='GDDDocument',
        ),
        migrations.DeleteModel(
            name='GDDDocumentComment',
        ),
        migrations.DeleteModel(
            name='KanbanTask',
        ),
        migrations.DeleteModel(
            name='LocalisationKey',
        ),
        migrations.DeleteModel(
            name='LocalisationTranslation',
        ),
        migrations.DeleteModel(
            name='PlaytestFeedback',
        ),
        migrations.DeleteModel(
            name='ProjectMilestone',
        ),
        migrations.DeleteModel(
            name='TranslationVote',
        ),
        migrations.DeleteModel(
            name='UserTranslationStats',
        ),
    ]
