# Generated by Django 5.2.12 on 2026-07-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20260629_1648'),
        ('core', '0041_workspacestate_remove_gdddatatable_project_and_more'),
    ]

    operations = [
    ]
