# Generated by Django 5.2.12 on 2026-07-03 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_merge_20260703_1148'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacestate',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_states', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='workspacestate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspacestate',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='workspacestate',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('key', 'user'), name='unique_user_workspace_state'),
        ),
        migrations.AddConstraint(
            model_name='workspacestate',
            constraint=models.UniqueConstraint(condition=models.Q(('organisation__isnull', False)), fields=('key', 'organisation'), name='unique_organisation_workspace_state'),
        ),
    ]
