# Generated by Django 5.2.12 on 2026-07-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_review_timestamp'),
        ('core', '0043_workspacestate_organisation_workspacestate_user_and_more'),
    ]

    operations = [
    ]
