# Generated by Django 5.2.12 on 2026-07-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_seed_default_roles'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='role',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.project'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('organisation', 'name'), name='unique_org_role_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'name'), name='unique_project_role_name'),
        ),
    ]
