# Generated by Django 5.2.12 on 2026-07-12 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_playtester_default_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationinvitation',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_invitation_assignments', to='core.role'),
        ),
    ]
