# Generated by Django 5.2.12 on 2026-07-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_merge_20260710_0041'),
        ('core', '0050_backfill_null_custom_roles'),
    ]

    operations = [
    ]
