# Generated by Django 5.2.12 on 2026-07-13 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_merge_20260712_2206'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='steam_appid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='steam_reviews_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlaytestFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('app', 'App'), ('steam', 'Steam')], default='app', max_length=10)),
                ('type', models.CharField(blank=True, choices=[('bug', 'Bug'), ('suggestion', 'Suggestion'), ('crash', 'Crash'), ('ui', 'UI')], default='', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=20)),
                ('build_version', models.CharField(blank=True, default='', max_length=50)),
                ('steam_review_id', models.CharField(blank=True, default='', max_length=32)),
                ('steam_author_id', models.CharField(blank=True, default='', max_length=32)),
                ('steam_author_name', models.CharField(blank=True, default='', max_length=100)),
                ('steam_voted_up', models.BooleanField(blank=True, null=True)),
                ('steam_playtime_minutes', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('converted_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('submitted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playtest_feedback', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playtest_feedback', to='core.project')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'steam')), fields=('project', 'steam_review_id'), name='unique_steam_review_per_project')],
            },
        ),
    ]
