# Generated by Django 5.2.12 on 2026-07-13 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_ui_type_to_ui_ux(apps, schema_editor):
    # The 'type' choice 'ui' was renamed to 'ui_ux'. choices aren't DB-enforced, so
    # convert any pre-existing rows so they don't render/filter as an unknown value.
    PlaytestFeedback = apps.get_model('core', 'PlaytestFeedback')
    PlaytestFeedback.objects.filter(type='ui').update(type='ui_ux')


def reverse_ui_ux_to_ui(apps, schema_editor):
    PlaytestFeedback = apps.get_model('core', 'PlaytestFeedback')
    PlaytestFeedback.objects.filter(type='ui_ux').update(type='ui')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_playtester_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playtestfeedback',
            options={'ordering': ['-is_pinned', '-submitted_at']},
        ),
        migrations.RemoveConstraint(
            model_name='playtestfeedback',
            name='unique_steam_review_per_project',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'news'), ('user', 'post'), ('user', 'review')},
        ),
        migrations.RemoveField(
            model_name='playtestfeedback',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='playtestfeedback',
            name='source',
        ),
        migrations.RemoveField(
            model_name='playtestfeedback',
            name='steam_author_id',
        ),
        migrations.RemoveField(
            model_name='playtestfeedback',
            name='steam_author_name',
        ),
        migrations.RemoveField(
            model_name='playtestfeedback',
            name='steam_playtime_minutes',
        ),
        migrations.RemoveField(
            model_name='playtestfeedback',
            name='steam_review_id',
        ),
        migrations.RemoveField(
            model_name='playtestfeedback',
            name='steam_voted_up',
        ),
        migrations.RemoveField(
            model_name='project',
            name='steam_appid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='steam_reviews_synced_at',
        ),
        migrations.AddField(
            model_name='like',
            name='playtest_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.playtestfeedback'),
        ),
        migrations.AddField(
            model_name='playtestfeedback',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playtestfeedback',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='playtestfeedback',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='playtestfeedback',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
        migrations.RunPython(migrate_ui_type_to_ui_ux, reverse_ui_ux_to_ui),
        migrations.AlterField(
            model_name='playtestfeedback',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('suggestion', 'Suggestion'), ('crash', 'Crash'), ('ui_ux', 'UI/UX'), ('performance', 'Performance'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'news'), ('user', 'playtest_feedback'), ('user', 'post'), ('user', 'review')},
        ),
    ]
