# Generated by Django 5.2.12 on 2026-07-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_feedback_priority_and_permission_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ci_build_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
