# Generated by Django 5.2.12 on 2026-07-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_project_integration_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ci_build_token',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_repo_url',
        ),
    ]
