# Generated by Django 5.2.12 on 2026-07-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_project_integration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='extra_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/logos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube',
            field=models.URLField(blank=True, default=''),
        ),
    ]
