# Generated by Django 5.2.12 on 2026-07-16 07:24

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_add_project_social_and_extra_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('news__isnull', True), ('playtest_feedback__isnull', True), ('post__isnull', False), ('review__isnull', True)), models.Q(('news__isnull', True), ('playtest_feedback__isnull', True), ('post__isnull', True), ('review__isnull', False)), models.Q(('news__isnull', False), ('playtest_feedback__isnull', True), ('post__isnull', True), ('review__isnull', True)), models.Q(('news__isnull', True), ('playtest_feedback__isnull', False), ('post__isnull', True), ('review__isnull', True)), _connector='OR'), name='like_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 10)), name='review_rating_between_0_and_10'),
        ),
    ]
