# Generated by Django 5.2.12 on 2026-07-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_review_like_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacestate',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
