# Generated by Django 5.2.12 on 2026-07-16 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_add_workspacestate_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-trending_score', '-timestamp'], name='post_trending_recent_idx'),
        ),
    ]
