# Generated by Django 5.2.12 on 2026-07-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20260719_1140'),
        ('core', '0061_perf_indexes_and_privacy_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to='api.interest'),
        ),
    ]
