# Generated by Django 5.2.12 on 2026-07-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20260719_1140'),
        ('core', '0062_post_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='tagged_reviews', to='api.interest'),
        ),
    ]
