# Generated by Django 5.2.12 on 2026-07-30 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Existing seeded Role rows have their `permissions` list frozen at creation time — without
# this backfill, no one in any pre-existing organisation could approve/reject/delete community
# translations, since the new keys only reach freshly-seeded roles going forward.
_NEW_KEYS = [
    'community_translation.approve',
    'community_translation.reject',
    'community_translation.delete',
]


def grant_community_translation_permissions(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    for role in Role.objects.all():
        perms = role.permissions or []
        # Anyone who could already approve the internal Devs Localisation Manager's suggestions
        # has the same editorial authority over the public community-translation surface — grant
        # them the equivalent new keys.
        if 'localisation.suggestion.approve' not in perms:
            continue
        already_delete_capable = (
            getattr(role, 'is_default_for', None) in ('owner', 'admin')
            or any(p.endswith('.delete') or p.endswith('.delete_any') for p in perms)
        )
        changed = False
        for key in _NEW_KEYS:
            if key == 'community_translation.delete' and not already_delete_capable:
                continue
            if key not in perms:
                perms.append(key)
                changed = True
        if changed:
            role.permissions = perms
            role.save(update_fields=['permissions'])


def revoke_community_translation_permissions(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    for role in Role.objects.all():
        perms = role.permissions or []
        if not any(k in perms for k in _NEW_KEYS):
            continue
        role.permissions = [p for p in perms if p not in _NEW_KEYS]
        role.save(update_fields=['permissions'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_review_interests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('namespace', models.CharField(blank=True, default='', max_length=120)),
                ('language', models.CharField(choices=[('Turkish', 'Turkish'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Japanese', 'Japanese'), ('Portuguese', 'Portuguese')], max_length=32)),
                ('text', models.TextField()),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='like_exactly_one_target',
        ),
        migrations.AddField(
            model_name='communitytranslation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_community_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitytranslation',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitytranslation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_translations', to='core.project'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'news'), ('user', 'playtest_feedback'), ('user', 'post'), ('user', 'review')},
        ),
        migrations.AddField(
            model_name='like',
            name='community_translation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.communitytranslation'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'community_translation'), ('user', 'news'), ('user', 'playtest_feedback'), ('user', 'post'), ('user', 'review')},
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('community_translation__isnull', True), ('news__isnull', True), ('playtest_feedback__isnull', True), ('post__isnull', False), ('review__isnull', True)), models.Q(('community_translation__isnull', True), ('news__isnull', True), ('playtest_feedback__isnull', True), ('post__isnull', True), ('review__isnull', False)), models.Q(('community_translation__isnull', True), ('news__isnull', False), ('playtest_feedback__isnull', True), ('post__isnull', True), ('review__isnull', True)), models.Q(('community_translation__isnull', True), ('news__isnull', True), ('playtest_feedback__isnull', False), ('post__isnull', True), ('review__isnull', True)), models.Q(('community_translation__isnull', False), ('news__isnull', True), ('playtest_feedback__isnull', True), ('post__isnull', True), ('review__isnull', True)), _connector='OR'), name='like_exactly_one_target'),
        ),
        migrations.AddIndex(
            model_name='communitytranslation',
            index=models.Index(fields=['project', 'language', 'key'], name='ct_proj_lang_key_idx'),
        ),
        migrations.AddIndex(
            model_name='communitytranslation',
            index=models.Index(fields=['project', 'key', 'language'], name='ct_proj_key_lang_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitytranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('project', 'key', 'language'), name='uniq_approved_ct_per_key_lang'),
        ),
        migrations.AddConstraint(
            model_name='communitytranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rejected'), _negated=True), fields=('project', 'key', 'language', 'author'), name='uniq_ct_author_per_key_lang'),
        ),
        migrations.RunPython(grant_community_translation_permissions, revoke_community_translation_permissions),
    ]
