# Generated by Django 5.2.12 on 2026-07-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_community_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitytranslation',
            name='note',
        ),
    ]
