# Generated by Django 5.2.12 on 2026-07-30 15:31

from django.db import migrations, models

# Round-1's CommunityTranslation.language stored these English display-name strings directly as
# the value. Duplicated here (rather than imported from api.locale_registry) is deliberately NOT
# done — migrations importing app constants that could change shape later is a known footgun, but
# this one mapping is small, frozen in time (it only ever describes round-1's exact 6-language
# state), and matches api.locale_registry.LEGACY_NAME_TO_CODE at the time this migration was
# written. If the registry's mapping ever changes, this migration's own copy must NOT follow it —
# it describes what the data looked like before this migration ran, not what it looks like now.
_LEGACY_NAME_TO_CODE = {
    'English': 'en',
    'Turkish': 'tr',
    'Spanish': 'es',
    'French': 'fr',
    'German': 'de',
    'Japanese': 'ja',
    'Portuguese': 'pt-BR',
}
_CODE_TO_LEGACY_NAME = {v: k for k, v in _LEGACY_NAME_TO_CODE.items()}
_DEFAULT_TARGET_CODES = ['tr', 'es', 'fr', 'de', 'ja', 'pt-BR']


def migrate_language_codes_forward(apps, schema_editor):
    CommunityTranslation = apps.get_model('core', 'CommunityTranslation')
    for name, code in _LEGACY_NAME_TO_CODE.items():
        CommunityTranslation.objects.filter(language=name).update(language=code)


def migrate_language_codes_reverse(apps, schema_editor):
    CommunityTranslation = apps.get_model('core', 'CommunityTranslation')
    for code, name in _CODE_TO_LEGACY_NAME.items():
        CommunityTranslation.objects.filter(language=code).update(language=name)


def migrate_blob_glossary_and_languages_forward(apps, schema_editor):
    """
    Two independent fixes to every WorkspaceState row's JSON blob:
      1. GlossaryTerm.translations was keyed by language DISPLAY NAME (e.g. {'Turkish': '...'})
         — once the app switches to locale codes everywhere, an unconverted glossary entry would
         silently stop matching (no error, the lock-term feature just goes dead). Rewrite those
         keys through the same mapping.
      2. Seed `translationLanguages`/`translationSourceLanguage` explicitly for any board that
         already has a non-empty key catalogue, so existing projects' configuration is visible
         and self-documenting in the new language-settings UI rather than invisibly defaulted
         (the backend's resolve_project_locales() fallback covers boards left unseeded, so this
         step is not strictly required for correctness — only for UI clarity).
    Bumps `version` on every touched row so a client with the board open in another tab gets a
    409 (and reconciles) rather than silently overwriting this rewrite.
    """
    WorkspaceState = apps.get_model('core', 'WorkspaceState')
    for state in WorkspaceState.objects.all().iterator():
        data = state.data or {}
        changed = False

        glossary = data.get('glossary') or []
        for term in glossary:
            translations = term.get('translations')
            if not isinstance(translations, dict):
                continue
            rewritten = {}
            for lang_key, value in translations.items():
                new_key = _LEGACY_NAME_TO_CODE.get(lang_key, lang_key)
                rewritten[new_key] = value
                if new_key != lang_key:
                    changed = True
            term['translations'] = rewritten

        if data.get('translationKeys') and not data.get('translationLanguages'):
            data['translationLanguages'] = [
                {'code': code, 'name': _CODE_TO_LEGACY_NAME.get(code, code)}
                for code in _DEFAULT_TARGET_CODES
            ]
            data['translationSourceLanguage'] = {'code': 'en', 'name': 'English'}
            changed = True

        if changed:
            state.data = data
            state.version = (state.version or 0) + 1
            state.save(update_fields=['data', 'version'])


def migrate_blob_glossary_and_languages_reverse(apps, schema_editor):
    WorkspaceState = apps.get_model('core', 'WorkspaceState')
    for state in WorkspaceState.objects.all().iterator():
        data = state.data or {}
        changed = False

        glossary = data.get('glossary') or []
        for term in glossary:
            translations = term.get('translations')
            if not isinstance(translations, dict):
                continue
            rewritten = {}
            for code_key, value in translations.items():
                old_key = _CODE_TO_LEGACY_NAME.get(code_key, code_key)
                rewritten[old_key] = value
                if old_key != code_key:
                    changed = True
            term['translations'] = rewritten

        if 'translationLanguages' in data or 'translationSourceLanguage' in data:
            data.pop('translationLanguages', None)
            data.pop('translationSourceLanguage', None)
            changed = True

        if changed:
            state.data = data
            state.version = (state.version or 0) + 1
            state.save(update_fields=['data', 'version'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_community_translation_drop_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitytranslation',
            name='language',
            field=models.CharField(max_length=35),
        ),
        migrations.AddField(
            model_name='communitytranslation',
            name='plural_forms',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(migrate_language_codes_forward, migrate_language_codes_reverse),
        migrations.RunPython(migrate_blob_glossary_and_languages_forward, migrate_blob_glossary_and_languages_reverse),
    ]
