# Generated by Django 5.2.12 on 2026-07-31 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_tighten_member_role_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playtestfeedback',
            index=models.Index(fields=['project', '-is_pinned', '-submitted_at'], name='ptf_proj_pin_sub_idx'),
        ),
    ]
