# Generated by Django 5.2.12 on 2026-08-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_post_poll_expires_at_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
