# Generated by Django 5.2.12 on 2026-08-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_review_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='platform',
        ),
        migrations.AddField(
            model_name='review',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='review',
            name='playtime_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
